### ISSUE TITLE
Not compatible with Mail 11.5

### ISSUE THREAD

**Issue by Shnub** [saagarjha/DetailsViewer#1]
I'd love to use this, but installing the Mail plugin produces this:

![Screen Shot 2019-11-13 at 10 55 18](https://user-images.githubusercontent.com/29605254/68753002-8e953380-0604-11ea-9d7b-18def91a9ac9.png)

I'm on 10.13.6.

Any chance of an update?

**Comment by saagarjha** [comment]
Short answer: add

```xml
<key>Supported10.13PluginCompatibilityUUIDs</key>
<array>
	<string># Mail 11.0 (3431); macOS 10.13 Beta (17A264c)</string>
	<string>C86CD990-4660-4E36-8CDA-7454DEB2E199</string>
</array>
```

to the Info.plist and recompile.

Long answer: I initially write this as a test to see if I could write a Mail plugin in Swift, so I haven't touched this for a while because Swift has removed every technique I can think of to get code execution at bundle load. I've been dragging my feet ever since because I've been waiting for someone to either add this back to the language or to get some free time and figure out how to hack this back in myself.

**Comment by Shnub** [comment]
Thank you.

Unfortunately, I'm not a developer and don't have Xcode. I tried adding that to the Info.plist in the Mail bundle, but it didn't change anything.

**Comment by saagarjha** [comment]
Maybe my ID is incorrect. Can you try running `defaults read /Applications/Mail.app/Contents/Info PluginCompatibilityUUID` and seeing if it gives you a different UUID?

**Comment by Shnub** [comment]
Nope, same ID. This is where I put the above plist entries:

![Screen Shot 2019-11-13 at 14 12 58](https://user-images.githubusercontent.com/29605254/68767632-49332f00-0621-11ea-9306-320fe4e45343.png)

**Comment by saagarjha** [comment]
Yeah, that looks about right; I’m not sure why it doesn’t work (maybe Console has some hints?) Unfortunately I can’t build the project anymore, so you’re going to have to wait until I can take another look at this :(

**Comment by saagarjha** [comment]
Oh, I should have probably notified you: I managed to get this to build now and it should work on macOS Catalina.
